name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node and Cache Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies and Build project
        run: |
          npm install
          npm run build --base=./

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4.6.2  # 从 v3 改为 v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: production-files
          path: ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RESUME_TOKEN }}
          publish_dir: ./dist
